name: test
services:
  store:
    type: compose
    volumes:
      agdata:
      agconfig:
    services:
      image: franzinc/agraph:latest
      command: /entrypoint.sh
      shm_size: 1g
      environment:
        AGRAPH_SUPER_USER: admin
        AGRAPH_SUPER_PASSWORD: password
        ENABLE_DATA_WRITE: "true"
        ENABLE_UPDATE: "true"
        ENABLE_UPLOAD: "true"
      volumes:
        - agdata:/agraph/data
        - agconfig:/agraph/etc

proxy:
  store:
    - db.lndo.site:10035
