# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ["v7.1.0", "v7.2.0"]
    steps:
      - uses: docker-practice/actions-setup-docker@master
      - run: df -h /dev/shm
      - run: docker run --shm-size 1g franzinc/agraph:${{ matrix.tag }} 

