# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ["v7.1.0", "v7.2.0"]
    steps:
      - uses: docker-practice/actions-setup-docker@master
      - run: df -h /dev/shm
      - run: docker run -d --shm-size 1g -p 10035:10035 franzinc/agraph:${{ matrix.tag }} 
      - run: curl http://localhost:10035
  compose:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ["v7.1.0", "v7.2.0"]
    steps:  
      - uses: actions/checkout@v2.3.5
      - uses: docker-practice/actions-setup-docker@master
      - run: df -h /dev/shm
      - run: docker-compose up -d
        env:
          TAG: ${{ matrix.tag }}
      - run: curl http://localhost:10035
